name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Secret in Action
      run: echo "The secret is ${{ secrets.CF_USERNAME }}"